server:
  port: 9801

spring:
  application:
    name: student-service-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka