spring:
  application:
   name: order-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    web:
      exposure:
        include: refresh
  health:
    circuitbreaker:
      enabled: true
logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG

resilience4j:
  circuitbreaker:
    instance:
      customer-serviceCB:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: 2