spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MadhuBrahmam4595/config-repo.git
          clone-on-start: true
          username: MadhuBrahmam4595
          password: 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
  application:
    name: MSConfigServer

server:
  port: 8888
